name: in_memory_headlines_client
description: InMemory implementation of the headlines client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies: 
  headlinehub_models:
    path: ../../headlinehub_models
  headlines_client:
    path: ../headlines_client

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
