name: headlineshub_headlines_client
description: headlinHub API implementaion of the headlineClient abstract class
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  headlines_client:
    path: ../headlines_client
  http: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
